server {
  listen 8080;
  root /app;

  location /assets/ {
    try_files $uri =404;
  }

  location /config {
    alias /app/config/;
    try_files $uri$args $uri$args/ =404;
  }

  location / {
    try_files $uri$args $uri$args/ /index.html;
  }
}
